language: r
warnings_are_errors: false
cache: packages
sudo: false
r_packages:
- curl
- jsonlite
- leafletR
r_github_packages: rladies/meetupr
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
env:
  global:
  - secure: AKHGXuztwUxK1qgFPTFNdOhU13uLIYNsMXGB40XaZjugBuXO006n7rKpGublZpbHostr4JOpDhxb3Nh9rZsycSb8JddYIvARv+MlSooyM2o051Hy9CB/GwqaSUFvB6zjM8rYNRJluY0yYKDv7S9QXJsKzdyl417HdPujETj8wbiFNKDQscz/u3ZFI39gjc+obO645fMR9ZdLrhH/zPy1dJQZFPKIPd+1TrMWkJKtkruFvrT4ijip+S5quXpk+EnBAGrPuu0qLOOlkzDh+g9K7vu9vGGc9sTXagg8AANIRipNlUSPgMQcZYVumzqzYXiOcsn5bb3KJDvgLGjRrwBv48A661Pl39bfSgJvQQZgqZeFDJ33LsEdCctCcEZy7VxlbHnaz6uk7aa4N1N4bgz9SlhUJbbKkhYp586l61V/MYsxLDH+k8QUHkE8SuGjqGP/lUnQPEPBn05vcUFMB/9vB+TooE5xMZJ/RcCHT1duqEkTlmNFF4F+3y7dmhN96pqx9UARFtM8VOxEdqAzQ8vJryPB181Trg7s4qs+bcH4WwQNosnowjhRjHoXgW7GAhvEofMOv3TcGyU6L8gWR8JQJmQnkWC9ecdZrtNexNdV2nxR6OY1IO1muO0kn85nVzhcothCrPJzJRcTkZDdsttNbuLXI8BAOj6Qzv40/Zj2slY=
  - secure: CoKlQiKjeMho3SEebE5jsE8Dso/n7AIcfp//PLNm/BbAqn4/KLVCjUVxAk3EhxHuj8nCI4Sznu22iURt/Xcf6z4mnXP6k0FNF/fZkcaH+DIcfT9fa5Sd65GosqxVIKknWTerUrNmA24r/xnHijNVJ/PgF6ktTlPKT5TRWGo1mL5njDiHIeAcdFCwXE59Iy8334c44NIHbyWJihsprQPhfnySNe3Yf0tTVRUnRN6cU7yWo0Sta2lp5VwOxml9tNrIVr5ItWVguwKQSDSQZanSh7+EDbuaEH/FzDPA4AZ62yNjCNFJl/hSo9/b3q63QbJJNb2CPWT0NDmVT6rSkQixdtyIfgiZNZfSAMppk3OemOZt9x4NdhvIJLe+sLgZWiSvn2qI7O0cusn8XaZUota98nJGvffs/Tj8X+gnqKlRx+DHYaSjhnJMfQhH/vs9+RNoXIdgTk86XiP6dJlKCVyxWcOnSF8JEbNiEeI7Tjrciv1Kk48bC5Kv3wJbV2ICY964zx0or+DB4pnNqYMzL8I25RDYJX4noVFJjHf2K13MVl50bnspm/qYlDnI21EUPPE59h87Sv+h7VMJjFO6Zz0QnG+T2dNlePhgCAhScZshSKDCc4IfXZ2jYwK8E1UmPVYmyYee/1ZyKjjKbpP4QmCY+mXovPLfaSRTnfMNAz4RIho=
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in R/meetup_token.rds.enc -out
  meetup_token.rds -d
